name: Check CLA Signature
on:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  check_cla:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        sparse-checkout: |
          licenses/cla-individual.md
        sparse-checkout-cone-mode: false
    - run: gh pr comment "$NUMBER" -b "@$USER Please sign the CLA"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.pull_request.number }}
        USER: ${{ github.actor }}

