name: Label issues
on:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  check_cla:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh pr comment "$NUMBER" -b "Please sign the CLA"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}

