# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Get branches
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}          
          script: |
            try {
              const response = await github.request('GET /repos/twlinks-ci-test/ci-test-repo/branches', {
                owner: 'twlinks-ci-test',
                repo: 'ci-test-repo'
              });
              //console.log(response);
              for(const branch of response.data) {
                if(branch.name.startsWith("create-pull-request") {
                  console.log(branch.name);
                }
              }
              const pullsReponse = await github.request('GET /repos/saqimtiaz/ci-test-repo/pulls', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'all',
                head: 'twlinks-ci-test:main'
              });
              console.log(pullsReponse.data);
            } catch (e) {
              console.log(e)
            }

