name: Check CLA Signature
on:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  check_cla:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - run: |
        if ! curl -s https://raw.githubusercontent.com/Jermolene/TiddlyWiki5/tiddlywiki-com/licenses/cla-individual.md | grep -o "@$USER,"; then
          gh pr comment "$NUMBER" -b "@$USER Please sign the CLA"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.pull_request.number }}
        USER: ${{ github.actor }}

