name: CLA Signed

on:
  pull_request_target:
    types:
      - opened
      - closed
    paths:
      - 'licenses/cla-individual.md'

jobs:
  check-signature-branch:
    if: (github.event.pull_request.merged != true) && (github.event.pull_request.user.login != github.repository_owner)
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - run: |
        if ! $BRANCH == "tiddlywiki-com"; then
          echo "This CLA signature targets the wrong branch"
          gh pr comment "$NUMBER" -b "@$USER Signatures to the CLA must target the `tiddlywiki-com` branch."
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.pull_request.number }}
        USER: ${{ github.actor }}
        BRANCH: ${{ github.event.pull_request.base.ref }}
      
